version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    ports:
      - 9200:9200
      # - 9300:9300
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - twitter
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
  #   ports:
  #     - 5601:5601
  #   volumes:
  #     - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   networks:
  #     - twitter
  #   depends_on:
  #     - elasticsearch
  keycloak:
    image: docker.io/bitnami/keycloak:22
    container_name: keycloak
    ports:
      - 1010:8080
    # volumes:
    #   - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # environment:
    #   - discovery.type=single-node
    #   - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - twitter

networks:
  twitter:
    name: twitter-network
