version: "3.7"

services:
  twitter-service-api:
    build: ../../twitter.api
    container_name: twitter-api
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    networks:
      - twitter
  
networks:
  twitter:
    name: twitter-network
    external: true