@elasticsearch = http://localhost:9200

###
GET {{elasticsearch}}

###
GET {{elasticsearch}}/_cat/health?v

###
GET {{elasticsearch}}/_cat/nodes?v

###
GET {{elasticsearch}}/_cat/indices?v

###
DELETE {{elasticsearch}}/tweets

###
PUT {{elasticsearch}}/tweets
Content-Type: application/json

{
    "settings": {
        "index": {
            "number_of_shards": 1,
            "number_of_replicas": 1 
        }
    },
    "mappings": {
        "properties": {
            "id": { "type": "integer" },
            "displayName": { "type": "keyword" },
            "username": { "type": "keyword" },
            "verified": {"type": "boolean"},
            "text": { "type": "text" },
            "image": { "type": "text" },
            "postDate": { "type": "date" }
      }
    }
}

###
GET {{elasticsearch}}/tweets

###
PUT {{elasticsearch}}/tweets/_doc/1
Content-Type: application/json

{
  "id":"1",
  "displayName": "Ahmed Helmy",
  "username":"helmy204",
  "verified": true,
  "text":"Hello from Twitter Clone with React!",
  "image":"https://media.giphy.com/media/26tk0jALFpsXmAF8c/giphy.gif",
  "postDate":"2022-12-08"
}

###
GET {{elasticsearch}}/tweets/_doc/1

###
GET {{elasticsearch}}/tweets/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "message": "my tweet"
    }
  }
}