@url = http://localhost:8080

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "displayName": "Ahmed Helmy",
    "username":"helmy204",
    "verified": true,
    "message":"Hello from Twitter Clone with React!",
    "image":"https://media.giphy.com/media/26tk0jALFpsXmAF8c/giphy.gif",
    "postDate":"2022-12-08"
}


###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "displayName": "Hala Khallaf",
    "username": "halakhallaf",
    "verified": false,
    "message": "I can tweet now",
    "image":"",
    "postDate":"2023-12-15"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "displayName":"Omar Salama",
    "username": "omarsalama",
    "verified": false,
    "message": "YOOO its working!",
    "image":"",
    "postDate":"2022-02-17"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"4",
    "user":"Yassine",
    "message": "tweet 3",
    "postDate":"2022-02-17"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"5",
    "user":"Talha",
    "message": "tweet 5",
    "postDate":"2022-02-17"
}

###
GET {{url}}/api/tweets

###
GET {{url}}/api/tweets/1

###
DELETE  {{url}}/api/tweets/1

###
GET {{url}}/api/tweets/getByUser?user=Jenny

###
GET {{url}}/api/tweets/getByMessage?message=tweet

###
GET {{url}}/api/tweets/getByMessage?message=my&amp;tweet