@url = http://localhost:8080

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"1",
    "user":"Helmy",
    "message": "This is my first tweet. I will see how this tweet will show.",
    "postDate":"2022-02-15"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"2",
    "user":"Ghadi",
    "message": "tweet 2",
    "postDate":"2022-02-16"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"3",
    "user":"Jenny",
    "message": "tweet 3",
    "postDate":"2022-02-17"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"4",
    "user":"Yassine",
    "message": "tweet 3",
    "postDate":"2022-02-17"
}

###
POST {{url}}/api/tweets
Content-Type: application/json

{
    "id":"5",
    "user":"Talha",
    "message": "tweet 5",
    "postDate":"2022-02-17"
}

###
GET {{url}}/api/tweets

###
GET {{url}}/api/tweets/1

###
DELETE  {{url}}/api/tweets/1

###
GET {{url}}/api/tweets/getByUser?user=Jenny

###
GET {{url}}/api/tweets/getByMessage?message=tweet

###
GET {{url}}/api/tweets/getByMessage?message=my&amp;tweet